### ISSUE TITLE
How can I disable CPM movement?

### ISSUE THREAD

**Issue by jkatz01** [Zinglish/quake3-movement-unity3d#17]
Pretty basic question but I would appreciate it if you tell me how to turn off CPM style air control, thanks!

**Comment by WiggleWizard** [comment]
You can't right now, it's hardcoded into the script. You'll have to revert the CPMA style to VQ3 manually by porting the VQ3 code yourself. Sorry!

**Comment by razzeeyy** [comment]
Actually you can try disabling CPM style air control by trying to tweak a few variables.

Look at this piece of code for reference:
https://github.com/WiggleWizard/quake3-movement-unity3d/blob/858675d65657b0e8ef36dca87099d1c9c3a6f081/CPMPlayer.cs#L222-L239

You'd need to set `airControl` to 0 (this is mainly the variable that gives that CPMA side-to-side strafe acceleration feel). And then if you set `sideStrafeAcceleration` to the value that's equal to `airAcceleration ` that should effectively disable the CPMA movement.

And maybe tweaking sideStrafeSpeed would do something too, like setting it to higher value if you wish. Although no certainty about last one.

Try experimenting with these suggestions @TheDominusCaseus see if it works out.
