### ISSUE TITLE
acceleration problem when in the air

### ISSUE THREAD

**Issue by tianbuliang** [Zinglish/quake3-movement-unity3d#4]
when walking on the ground , it works fine. But when i jump and press the forward key, the speed increase fast and soon reach to 50ups.
i already follow the setting step to set the Gravity and the Sensitivity of controls to a very high number. But it doesn't solve the problem.

**Comment by scnoobi** [comment]
not an issue. its got to do with air acceleration you should change it to something like 0.05

**Comment by Zinglish** [comment]
You'll definitely have to fiddle around with the properties, this wasn't exactly a fantastic 1 to 1 conversion since it's missing the collision port
