### ISSUE TITLE
Possible copy-paste issue CmdScale

### ISSUE THREAD

**Issue by atil** [Zinglish/quake3-movement-unity3d#5]
In CmdScale, line 382
`if(Mathf.Abs(_cmd.rightMove) > max)
            max = (int)Mathf.Abs(_cmd.forwardMove);`

`_cmd.forwardMove` will probably be `_cmd.rightMove`

**Comment by Zinglish** [comment]
Good spot! I should have seen that but didn't do any quality control checking on my part.

Fixed in 4c39c4d83ad1f32f2787eb2ef44d6a23cbd53cb2

Thanks!
